# Generated by Django 6.0 on 2026-03-29 06:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='college.department'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(choices=[('ALL', 'All Students'), ('SEMESTER', 'By Semester'), ('DEPARTMENT', 'By Department'), ('INDIVIDUAL', 'Individual Student'), ('GLOBAL', 'Global')], default='GLOBAL', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='semester',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='notification',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_notifications', to='college.student'),
        ),
    ]
