# Generated by Django 6.0 on 2026-03-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_profiles/'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_profiles/'),
        ),
    ]
